controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    # default_kp: 1000.0
    # default_kd: 10.0

    # Notes: https://github.com/ros-controls/ros2_controllers
    # Examples: https://github.com/ros-controls/ros2_control_demos
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
  
