controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controllers:
  ros__parameters:
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FL_Ankle
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - FR_Ankle
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HL_Ankle
      - HR_HAA
      - HR_HFE
      - HR_KFE
      - HR_Ankle

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
